### ISSUE TITLE
PHP catchable fatal error on Moodle 3.1

### ISSUE THREAD

**Issue by ColinBruneau** [Kylegoslin/moodle-block_faces#3]
Hi,

This bloc was working great so far with Moodle 3.1 but now when I click on "Show All Faces" I get a PHP catchable fatal error. 
I tried removing the plugin and reinstalling it but still the same. 
Any idea what to do? maybe remove something in the database?

Colin

**Comment by ColinBruneau** [comment]
Hello again,
After a few hours digging into the code, I found out that one of my users was deleted but was still referenced in a group. So the function print_single_face in renderFaces.php would crash when trying to get the user picture.
I added this line as a protection
if (!user) return '';
And it worked!
I believe the bug is mostly due to a user deleted not being removed from a group but you might be interested with this fix.
Cordially,
Colin

**Comment by Kylegoslin** [comment]
Thanks for that Colin, this has been added into the latest release!

Kyle.
