### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by behoof** [Kylegoslin/moodle-block_faces#5]
After clicking on faces 
and subsequently clicking on a student
and clicking on the faces link in the block
It ends with an error message (coding error)

**Comment by behoof** [comment]
Using moodle 3.4

**Comment by Kylegoslin** [comment]
Current version is now for Moodle 3.5

**Comment by behoof** [comment]
TOP!
 Will install it as soon as it is available in moodle plugins directory.
