### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by behoof** [Kylegoslin/moodle-block_faces#7]
L.s.

How to change the title of the block? I changed the language table, but no change.
Bug: Title of block cannot be changed thorugh de language tables.
Suggestion: change name in the block (configration) as well

Bert

**Comment by Kylegoslin** [comment]
Hello Bert,

Line 45, on https://github.com/Kylegoslin/moodle-block_faces/blob/master/block_faces.php

Just updated it to pull from the lang file. This should hopefully solve the issue for you.


Kyle.

**Comment by behoof** [comment]
THX!

Van: Kyle <notifications@github.com>
Beantwoorden - Aan: Kylegoslin/moodle-block_faces <reply@reply.github.com>
Datum: vrijdag 17 augustus 2018 om 12:31
Aan: Kylegoslin/moodle-block_faces <moodle-block_faces@noreply.github.com>
CC: "bert@vanderhooft.com" <bert@vanderhooft.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Kylegoslin/moodle-block_faces] Title (#7)


Hello Bert,

Line 45, on https://github.com/Kylegoslin/moodle-block_faces/blob/master/block_faces.php

Just updated it to pull from the lang file. This should hopefully solve the issue for you.

Kyle.

**Comment by Kylegoslin** [comment]
Thanks, all the best,


Kyle.
