### ISSUE TITLE
Data Breach Risk

### ISSUE THREAD

**Issue by behoof** [Kylegoslin/moodle-block_faces#8]
A deep link shows - without login - all the faces. Thats a risk for Data Breach and hurting privacy. 

e.g 
https://www.site/blocks/faces/showfaces/show.php?cid=276

Can you correct that? THX!

Bert

**Comment by Kylegoslin** [comment]
What version of the block do you currently have?

**Comment by Kylegoslin** [comment]
That particular page does require a login, but I noticed on the site you are running you have a Guest account that is providing access to things. Have you modified to block permissions?

**Comment by behoof** [comment]
Hi Kyle, 

I'm using Moodle 3.5.1+ (Build: 20180817) and Faces 2.0 (2018071900). 
Now Guest access is disabled, but the behaviour remains.
I cannot find in permissions the right for viewing the Faces content

Bert

**Comment by Kylegoslin** [comment]
Hello Bert,

At the minute, Faces currently is implemented to allow the block to be added or not for a given user account type. A finer grained "view faces" is not implemented. 

If you look in Site Admin -> Users -> Permissions for the account type that is viewing the block, What permission does the user account have? Can they add the block or not?

Kyle

**Comment by behoof** [comment]
Kyle,

It is not about the right to add the block. When I view the page with participants in Faces, I had the  habit to share the “show the faces” url with other participants, assuming that they had to login.

But when I share the url, anybody can change the cid number at the end of the url! By doing so everybody can detect who is attending which course. Even when I suppose that a moodle site uses the highly appreciated Faces block, I can scan their students! So its violating privacy rights.

Bert van der Hooft


________________________________
Van: Kyle <notifications@github.com>
Verzonden: donderdag, november 8, 2018 11:11 AM
Aan: Kylegoslin/moodle-block_faces
CC: Bert van der Hooft; Author
Onderwerp: Re: [Kylegoslin/moodle-block_faces] Data Breach Risk (#8)


Hello Bert,

At the minute, Faces currently is implemented to allow the block to be added or not for a given user account type. A finer grained "view faces" is not implemented.

If you look in Site Admin -> Users -> Permissions for the account type that is viewing the block, What permission does the user account have? Can they add the block or not?

Kyle

**Comment by Kylegoslin** [comment]
I installed a fresh installation of Moodle 3.5 with the Faces block. When the URL is accessed directly with the user logged out, a login is prompted.

Can you attempt to replicate this issue?

Thanks

**Comment by Kylegoslin** [comment]
The require_login would check that the user has logged in.

I made a change to the git code that will check to see if the user has permissions to view the course. If they can view the course then they can view the faces.

Try pull the code and see does that solve it for you.

**Comment by behoof** [comment]
Super! It works good!
Thx

Met vriendelijke groet,

Bert van der Hooft
Telefoon 06 11 11 9405

________________________________
Van: Kyle <notifications@github.com>
Verzonden: maandag, november 12, 2018 12:26 PM
Aan: Kylegoslin/moodle-block_faces
CC: Bert van der Hooft; Author
Onderwerp: Re: [Kylegoslin/moodle-block_faces] Data Breach Risk (#8)


The require_login would check that the user has logged in.

I made a change to the git code that will check to see if the user has permissions to view the course. If they can view the course then they can view the faces.

Try pull the code and see does that solve it for you.

**Comment by Kylegoslin** [comment]
Thanks for that. The release is now on Moodle and I've added you into the credits for spotting this.

Kyle.

**Comment by behoof** [comment]
TOP! Compliments.
